### ISSUE TITLE
ATP-Equivalent Credential Request

### ISSUE THREAD

**Issue by rceleste125** [Open-Credentialing-Initiative/OCI-Change-Requests#4]
Part of the original PDG Change request approved by Steering.
https://github.com/Open-Credentialing-Initiative/OCI-Change-Requests/issues/1

https://github.com/Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria/pull/64
https://github.com/Open-Credentialing-Initiative/Credential-Issuer-Conformance-Criteria/pull/16
https://github.com/Open-Credentialing-Initiative/schemas/pull/10

**Comment by bluesteens** [comment]
**Triage:**

- [x] Is Issue appropriate for OCI Architecture
- [ ] Create Steering-level Summary of request
- [x] Assign **Size**
- [x] Assign **Priority**
- [x] Assign **Label** (if needed)
- [x] OCI affected Artifacts Identified
- [ ] Assign **Triage - Artifact Version Target** (v x.x.x Milestone)
- [ ] Assign **Triage - Interop Profile Version Target** (v x.x.x Milestone)
- [ ] Create sub-project (if needed)


**Affected Parties (help determine Sunrise/Sunset):**
    
- [ ] Trading Partners
- [ ] Issuers 
- [ ] Wallet Solutions
- [ ] PI Verification Solutions

**Comment by rceleste125** [comment]
Affected Artifacts:

OCI Schema document
Wallet Conformance Criteria
Issuer Conformance Criteria

**Comment by alexcolganLD** [comment]
https://github.com/Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria/pull/64
https://github.com/Open-Credentialing-Initiative/Credential-Issuer-Conformance-Criteria/pull/16
https://github.com/Open-Credentialing-Initiative/schemas/pull/10

**Comment by bluesteens** [comment]
July, 27: to be released in Digital Wallet Criteria v3.3.0,  interop profile v3.2.0; Credential Issuer Criteria v2.1.1, Credential Schema criteria v1.2.0; new JSON-LD schemas v1.0.0
