### ISSUE TITLE
DSCSA Authority Credential Request

### ISSUE THREAD

**Issue by rceleste125** [Open-Credentialing-Initiative/OCI-Change-Requests#5]

**Comment by bluesteens** [comment]
**Triage:**

- [x] Is Issue appropriate for OCI Architecture
- [ ] Create Steering-level Summary of request
- [x] Assign **Size**
- [x] Assign **Priority**
- [x] Assign **Label** (if needed)
- [ ] OCI affected Artifacts Identified
- [ ] Assign **Triage - Artifact Version Target** (v x.x.x Milestone)
- [ ] Assign **Triage - Interop Profile Version Target** (v x.x.x Milestone)
- [ ] Create sub-project (if needed)


**Affected Parties (help determine Sunrise/Sunset):**
    
- [ ] Trading Partners
- [ ] Issuers 
- [ ] Wallet Solutions
- [ ] PI Verification Solutions

**Comment by rceleste125** [comment]
Response from PDG regarding Org Type in DSCSA Authority Credential:

Thanks for submitting your change request on behalf of OCI. We appreciate OCI sharing your consiiderations regarding issues that cross into policy areas. 

In reviewing OCI's change request and the work of the Credentialing WG, we realized that the original PDG Change Request to OCI includes the following request:  "PDG requests OCI to develop "DSCSA Authority" Credential specifications with identical claims as the ATP Credential (excluding Organization Type)."  

The request to exclude "Organization Type" was the recommended consensus of the Credentialing WG after exhaustive discussions about the "Organization Type" claim (called "Authority Jurisdiction" at the time). The team concluding that there was no clear benefit to the information, preferring to rely on the Subject attributes in the credential and the DSCSA Authority List that would be maintained by PDG as recommended in the "DSCSA Authorities" section of Chapter 6 of the PDG Bluprint. The recommendation of the WG was subsequently approved by the Interoperability Committee and PDG General Membership. 

This evaluation of the prior work of the Credentialing WG and PDG Change request seems to confirm that "Organization Type" is not needed in the approved DSCSA Authority list or in the DSCSA Authority Credential. Given this background information, do you believe there is enough trading partner support to re-open the conversation in the WG?

**Comment by rceleste125** [comment]
1. Create DSCSA Authority Credential schema & Conformance Criteria
2. Inform PDG, until the PDG list is available: Issuers can not issue these credentials

Note: Wallets depend on issuers to revoke the credentials of entities removed from the PDG list.

**Comment by bluesteens** [comment]
July, 27: to be released in Digital Wallet Criteria v3.3.0, interop profile v3.2.0; Credential Issuer Criteria v2.1.1, Credential Schema criteria v1.2.0; new JSON-LD schemas v1.0.0
